export {type ContactItemDto} from './contacts/contacts'
export {type QuestionItemDto} from './faq/faq'
export {type NewsItemDto} from './news/news'
export {type StudentItemDto} from './students/students'
export {type UserRegisterData} from './user/user'